### PR TITLE
fixed bug in generate_data and adapted tests

### LINKED ISSUE #28: Bug in `generate_data()`
To do:

- [x] Write a test that can show that there is this bug
- [x] Fix the problem (using suggested code below)
- [x] Ensure all tests pass
- [x] Add a `NEWS` entry

Tobias Mielke found a (likely) bug in our package:

> I might have detected a small bug in your code, which I would like to raise to your awareness. The function currently has:
> 
> result$type_of_event <- 1L + stats::rbinom(n = n, size = 2,prob = haz/haz_all)
> 
> If you test this code, you’ll see that there will be some confusion within R on the length of your generated data (n), the probability statement (prob) and the size. An alternative to your implementation might be the one below.
> 
> typeOfEvent=runif(n,min=0,max=1)
> probs=cumsum(haz/haz_all)
> result$type_of_event=rep(3,n)
> result$type_of_event[which(typeOfEvent<probs[1])]=1
> result$type_of_event[which(typeOfEvent>probs[1]&typeOfEvent>probs[2])]=2

I think he has a point here, and Regina Stegherr agress as well. We propose to replace

> result$type_of_event <- 1L + stats::rbinom(n = n, size = 2, prob = haz/haz_all)

through

> result$type_of_event <- sample(1:3, size = n, prob = haz / haz_all, replace = TRUE).

Simple exploration like

haz <- c(0.2, 0.3, 0.5)
haz_all <- sum(haz)
table(sample(1:3, size = 10^6, prob = haz / haz_all, replace = TRUE))/10^6

seems to show that this does the right thing.

### PR DESCRIPTION
**Pull request by kuenzelt**
closes #28

### CODE REVIEW

File: tests/testthat/test-generate_data.R [hunk 1]
```diff
@@ -12,3 +12,17 @@ test_that("generate_data works as expected", {
   expect_identical(result$id, 1:10)
   expect_integer(result$type_of_event, lower = 0, upper = 3, any.missing = FALSE)
 })
+
+test_that("show bug in v1 of generate_data", {
```
Comment (danielinteractive) [inline tests/testthat/test-generate_data.R:16]:
```suggestion
test_that("generate_data correctly ... ", {
```
and in the `...` part describe what it is doing correctly / in which special case

**Review by danielinteractive — COMMENTED** [review]
Super, plus we need the `NEWS` entry

File: NEWS.md [hunk 2]
```diff
@@ -7,3 +7,14 @@
...
+
+### bug fixes
+
+- changed the way data is generated in function generate_data:
+
+  result$type_of_event <- 1L + stats::rbinom(n = n, size = 2, prob = haz/haz_all)
+
+  was replaced with
+
+  result$type_of_event <- sample(1:3, size = n, prob = haz / haz_all, replace =      TRUE).
```
Comment (danielinteractive) [inline NEWS.md:20]: Better to keep this without code and high level - what is the functionality that was wrong before and is now fixed?

File: NEWS.md [hunk 3]
```diff
@@ -7,3 +7,14 @@
 
 - Estimators that do not account for competing events (incidence proportion, incidence density, Inverse Kaplan Meier).
 - Estimators accounting for competing events (incidence proportion accounting for competing events and Aalen-Johansen, both first with death only as hard competing event, or using all competing events).
+
+
+### bug fixes
```
Comment (danielinteractive) [inline NEWS.md:12]: this needs to go on top, under the new version tag

**Review by danielinteractive — APPROVED** [review]
Thanks @kuenzelt , I just did some last touches (version update, minor polishing on the NEWS). Good to merge as soon checks pass, and then you can build the package and submit to CRAN. Please let me know if you have any questions
